on:
  push:
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwsh -Command 'Install-Module -Name AWS.Tools.SimpleSystemsManagement -Force'
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::987868780346:role/github-actions-systemsmanager
      - run: pwsh -File get-aws-systemsmanager-publicdocs.ps1
      - uses: EndBug/add-and-commit@v7 
        with:
          message: Updating Systems Manager documents
          author_name: Trevor Sullivan
          author_email: trevor@trevorsullivan.net
