on:
  push:
  workflow_dispatch:

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwsh -Command 'Install-Module -Name AWS.Tools.SimpleSystemsManagement -Force'
      - run: pwsh -File get-aws-systemsmanager-publicdocs.ps1
      - uses: EndBug/add-and-commit@v7 
        with:
          message: Updating Systems Manager documents
          author_name: Trevor Sullivan
          author_email: trevor@trevorsullivan.net
